---
# Configuración del Notification Service
spring:
  application:
    name: notification-service

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:demo@example.com}
    password: ${EMAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://service-registry:8761/eureka}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /notification/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Notification Service API
    description: Microservicio para gestión de notificaciones
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    uy.bcu.notification: DEBUG
