---
# Configuración del Usuario Service
spring:
  application:
    name: usuario-service

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        initial-interval: 2000
        multiplier: 1.5
        max-attempts: 6

  datasource:
    url: ${DATABASE_URL:jdbc:oracle:thin:@oracle:1521:xe}
    username: ${DATABASE_USER:system}
    password: ${DATABASE_PASSWORD:oracle}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

server:
  port: 8081

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://service-registry:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /usuario/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Usuario Service API
    description: Microservicio para gestión de usuarios
    version: 1.0.0

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
