# Configuración del API Gateway
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}

# OpenAPI/Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Usuario Service
        url: /usuario/v3/api-docs
      - name: Product Service
        url: /producto/v3/api-docs
      - name: Order Service
        url: /pedido/v3/api-docs
      - name: Notification Service
        url: /notification/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
