# Configuración para entorno Docker
spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:1521:xe
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

# Configuración específica para contenedores
logging:
  level:
    uy.bcu.example: INFO
    root: WARN
