# Configuración para entorno de producción
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:oracle:thin:@oracle:1521:xe}
    username: ${DATABASE_USER:system}
    password: ${DATABASE_PASSWORD:oracle}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        cache:
          use_second_level_cache: true
          use_query_cache: true

# Configuración de seguridad para producción
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# Logging optimizado para producción
logging:
  level:
    root: WARN
    uy.bcu.example: INFO
  appender:
    loki:
      url: ${LOKI_URL:http://loki:3100/loki/api/v1/push}
