# Configuración del Product Service
spring:
  application:
    name: product-service

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

  datasource:
    url: ${DATABASE_URL:jdbc:oracle:thin:@oracle:1521:xe}
    username: ${DATABASE_USER:system}
    password: ${DATABASE_PASSWORD:oracle}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /producto/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Product Service API
    description: Microservicio para gestión del catálogo de productos
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
