# Configuración del Config Server
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:./config-repo
          default-label: main
        native:
          search-locations: classpath:/config
  profiles:
    active: native

server:
  port: 8888

logging:
  level:
    org.springframework.cloud.config: DEBUG
