# Configuración del Usuario Service
spring:
  application:
    name: usuario-service

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /usuario/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Usuario Service API
    description: Microservicio para gestión de usuarios
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
